name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        node: [ "12", "14", "16", "17" ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
        cache: "npm"
    - name: Install dependencies
      run: |
        npm install -g npm
        npm ci
    - name: Build package
      run: |
        npm run build
    - name: Test
      run: |
        npm test
